import { ImageMapType } from "../types";

export const images: ImageMapType = {
    "Luke Skywalker": "1.jpg",
    "C-3PO": "2.jpg",
    "R2-D2": "3.jpg",
    "Darth Vader": "4.jpg",
    "Leia Organa": "5.jpg",
    "Owen Lars": "6.jpg",
    "Beru Whitesun lars": "7.jpg",
    "R5-D4": "8.jpg",
    "Biggs Darklighter": "9.jpg",
    "Obi-Wan Kenobi": "10.jpg",
    "Anakin Skywalker": "11.jpg",
    "Wilhuff Tarkin": "12.jpg",
    Chewbacca: "13.jpg",
    "Han Solo": "14.jpg",
    Greedo: "15.jpg",
    "Jabba Desilijic Tiure": "16.jpg",
    "Wedge Antilles": "17.jpg",
    "Jek Tono Porkins": "18.jpg",
    Yoda: "19.jpg",
    Palpatine: "20.jpg",
    "Boba Fett": "21.jpg",
    "IG-88": "22.jpg",
    Bossk: "23.jpg",
    "Lando Calrissian": "24.jpg",
    Lobot: "25.jpg",
    Ackbar: "26.jpg",
    "Mon Mothma": "27.jpg",
    "Arvel Crynyd": "28.jpg",
    "Wicket Systri Warrick": "29.jpg",
    "Nien Nunb": "30.jpg",
    "Qui-Gon Jinn": "31.jpg",
    "Nute Gunray": "32.jpg",
    "Finis Valorum": "33.jpg",
    "Padmé Amidala": "34.jpg",
    "Jar Jar Binks": "35.jpg",
    "Roos Tarpals": "36.jpg",
    "Rugor Nass": "37.jpg",
    "Ric Olié": "38.jpg",
    Watto: "39.jpg",
    Sebulba: "40.jpg",
    "Quarsh Panaka": "41.jpg",
    "Shmi Skywalker": "42.jpg",
    "Darth Maul": "43.jpg",
    "Bib Fortuna": "44.jpg",
    "Ayla Secura": "45.jpg",
    "Ratts Tyerel": "46.jpg",
    "Dud Bolt": "47.jpg",
    Gasgano: "48.jpg",
    "Ben Quadinaros": "49.jpg",
    "Mace Windu": "50.jpg",
    "Ki-Adi-Mundi": "51.jpg",
    "Kit Fisto": "52.jpg",
    "Eeth Koth": "53.jpg",
    "Adi Gallia": "54.jpg",
    "Saesee Tiin": "55.jpg",
    "Yarael Poof": "56.jpg",
    "Plo Koon": "57.jpg",
    "Mas Amedda": "58.jpg",
    "Gregar Typho": "59.jpg",
    Cordé: "60.jpg",
    "Cliegg Lars": "61.jpg",
    "Poggle the Lesser": "62.jpg",
    "Luminara Unduli": "63.jpg",
    "Barriss Offee": "64.jpg",
    Dormé: "65.jpg",
    Dooku: "66.jpg",
    "Bail Prestor Organa": "67.jpg",
    "Jango Fett": "68.jpg",
    "Zam Wesell": "69.jpg",
    "Dexter Jettster": "70.jpg",
    "Lama Su": "71.jpg",
    "Taun We": "72.jpg",
    "Jocasta Nu": "73.jpg",
    "R4-P17": "74.jpg",
    "Wat Tambor": "75.jpg",
    "San Hill": "76.jpg",
    "Shaak Ti": "77.jpg",
    Grievous: "78.jpg",
    Tarfful: "79.jpg",
    "Raymus Antilles": "80.jpg",
    "Sly Moore": "81.jpg",
    "Tion Medon": "82.jpg",
};
